[package]
name = "graph-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "memory-graph"
path = "src/main.rs"

[dependencies]
graph-core = { path = "../graph-core" }
graph-store = { path = "../graph-store" }
graph-lang-rust = { path = "../graph-lang-rust" }
clap.workspace = true
ignore.workspace = true
anyhow.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
graph-store = { path = "../graph-store" }
redb.workspace = true
