[package]
name = "graph-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
graph-core = { path = "../graph-core" }
redb.workspace = true
serde.workspace = true
sha2.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
graph-lang-rust = { path = "../graph-lang-rust" }
proptest.workspace = true
